### ISSUE TITLE
Please consider mentioning my Ansible Galaxy role for installing Java

### ISSUE THREAD

**Issue by bviktor** [whichjdk/whichjdk.com#23]
(Shameless plug alert)

Hi,

I've made an Ansible Galaxy role for installing Java:

https://galaxy.ansible.com/bviktor/java
https://github.com/noobient/ansible-galaxy-java

Which provides an (I think) pretty convenient way to install various versions of Java in Ansible playbooks. You just specify flavor (you call them distros), and LTS version number, and that's it.

```yml
- include_role:
    name: bviktor.java
  vars:
    version: 11
    flavor: temurin
```

It's not necessarily for the average user, it's more of a deployment thing, it's obviously up to you to decide, you might find it worthwhile to mention on your site.

Thanks.
